-- Execute uma vez no SQL Editor do Supabase.

create table if not exists public.turnosmart_production_history (
  id bigint generated by default as identity primary key,
  report_date date,
  shift text,
  scope text,
  report_text text not null,
  machines jsonb default '[]'::jsonb,
  saved_at timestamptz default now()
);

create index if not exists idx_turnosmart_prod_date
  on public.turnosmart_production_history(report_date);

create table if not exists public.turnosmart_powerbi_history (
  id bigint generated by default as identity primary key,
  report_date date,
  shift text,
  machine text not null,
  product text,
  oee numeric,
  raw_data jsonb,
  saved_at timestamptz default now()
);

create index if not exists idx_turnosmart_pbi_machine_date
  on public.turnosmart_powerbi_history(machine, report_date);

-- O acesso do app passa somente pela Function da Vercel usando SERVICE_ROLE.
alter table public.turnosmart_production_history enable row level security;
alter table public.turnosmart_powerbi_history enable row level security;
